apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: poseidon1-public-repo-app1
  namespace: gitops-developers
spec:
  destination:
    namespace: poseidon1-dev
    server: 'https://kubernetes.default.svc'
  source:
    repoURL: 'https://github.com/TeamPoseidonOCP/poseidon1_public_repo.git'
    path: poseidon1-public-repo-app1
    targetRevision: HEAD
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
      allowEmpty: true
  project: poseidon1
